---

# Basic
name: "Vv's"
description: 
"
每一天都是新的开始😊
天外有天，山外有山，人外有人，不可骄傲自满。
天各有空，山各有峰，人各有志，不可妄自菲薄。
"

# URL
url: " "
#baseurl: ""
permalink: /:year/:month/:day/:title.html

# Markdown
markdown: kramdown

# Navigation
nav:
 - name: "About"
   href: "/about"

 - name: "GitHub"
   href: "https://github.com/Vv1222/vv1222.github.com"


# Sass
sass:
 style: :compressed

# Excerpt
excerpt_separator: <!-ex->

#Gems
gems: [jekyll-paginate]
paginate: 10
paginate_path: "/page:num/"

# Scopes
defaults:
 -
  scope:
   path: ""
   type: "pages"
  values:
   layout: "page"
 -
  scope:
   path: ""
   type: "posts"
  values:
   layout: "post"
---
